# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       geuzen-ux-theme
Summary:    Geuzen UX Theme
Version:    0.0.2
Release:    1
Group:      System/GUI/Other
License:    Restricted
URL:        http://www.meego.com
Source0:    %{name}-%{version}.tar.bz2
Source100:  geuzen-ux-theme.yaml
BuildRequires:  pkgconfig(QtCore) >= 4.6.0


%description
Tablet Theme

Requires: %{name} >= %{version}
Requires: libqtcore4




%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
/usr/share/themes/1024-600-10
# >> files
# << files


