# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       meego-ux-theme
Summary:    MeeGo UX Theme
Version:    999.999.999
Release:    1
Group:      System/GUI/Other
License:    None
URL:        http://www.no.such.url.exists
Source0:    %{name}-%{version}.tar.bz2
Source100:  meego-ux-theme.yaml


%description
Tablet Theme Package Placeholder to avoid conclicts




%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
/usr/share/themes/do-not-install-meego-ux-theme
# >> files
# << files


