# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       geuzen-ux-panels
Summary:    Geuzen UX Panels Interface
Version:    0.0.1.7
Release:    1
Group:      System/GUI/Other
License:    Apache 2.0
URL:        http://moui.sf.net
Source0:    %{name}-%{version}.tar.bz2
Source100:  geuzen-ux-panels.yaml
Requires:   %{name} >= %{version}
Requires:   meegolabs-ux-components >= 0.2.8.1
Requires:   meego-ux-components >= 0.2.8.11
Requires:   meego-ux-theme
Requires:   meego-ux-appgrid
Requires:   geuzen-ux-daemon
Requires:   meego-ux-sharing-qml
Requires:   meego-ux-sharing-qml-ui
Requires:   meego-ux-settings >= 0.3.5
BuildRequires:  pkgconfig(QtCore) >= 4.7.1
Obsoletes:   meego-ux-panels


%description
Panel core infrastructure for the Geuzen UX



%package friends
Summary:    Friends Panel
Group:      System/GUI/Other
Requires:   %{name} = %{version}-%{release}
Requires:   meego-ux-content
Requires:   meego-ux-settings-socialweb

%description friends
Panel that surfaces your friends social networking activity, emails, and IMs

%package web
Summary:    Web Panel
Group:      System/GUI/Other
Requires:   %{name} = %{version}-%{release}

%description web
Panel that surfaces your browser activity

%package video
Summary:    Video Panel
Group:      System/GUI/Other
Requires:   %{name} = %{version}-%{release}
Requires:   meego-app-video
Requires:   meego-ux-media

%description video
Panel that surfaces your video content

%package photos
Summary:    Photos Panel
Group:      System/GUI/Other
Requires:   %{name} = %{version}-%{release}
Requires:   meego-app-photos
Requires:   meego-ux-media >= 0.2.16

%description photos
Panel that surfaces your photo content

%package music
Summary:    Music Panel
Group:      System/GUI/Other
Requires:   %{name} = %{version}-%{release}
Requires:   meego-app-music
Requires:   meego-ux-media

%description music
Panel that surfaces your music content

%package ifcfg
Summary:    Ifconfig Panel
Group:      System/GUI/Other
Requires:   %{name} = %{version}-%{release}
Requires:   geuzen-qml-utils

%description ifcfg
Panel that displays network information

%package mytablet
Summary:    My Tablet Panel
Group:      System/GUI/Other
Requires:   %{name} = %{version}-%{release}
Requires:   meego-ux-settings
Requires:   meego-ux-media
Requires:   connman-qt-declarative

%description mytablet
Panel that surfaces information about your Geuzen Tablet

%package meta-tablet
Summary:    Tablet Panels meta package
Group:      System/GUI/Other
Requires:   %{name} = %{version}-%{release}
Requires:   geuzen-ux-panels-friends >= %{version}
Requires:   geuzen-ux-panels-web >= %{version}
Requires:   geuzen-ux-panels-video >= %{version}
Requires:   geuzen-ux-panels-photos >= %{version}
Requires:   geuzen-ux-panels-music >= %{version}
Requires:   geuzen-ux-panels-mytablet >= %{version}

%description meta-tablet
Meta package to pull in the panels used in the Geuzen Tablet UX


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post






























%files
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/MeeGo/Panels
%{_datadir}/geuzen-ux-panels/main.qml
%{_datadir}/geuzen-ux-panels/panels/.keep
# >> files
# << files


%files friends
%defattr(-,root,root,-)
%{_datadir}/geuzen-ux-panels/friends
%{_datadir}/geuzen-ux-panels/panels/friends.panel
# >> files friends
# << files friends

%files web
%defattr(-,root,root,-)
%{_datadir}/geuzen-ux-panels/web
%{_datadir}/geuzen-ux-panels/panels/web.panel
# >> files web
# << files web

%files video
%defattr(-,root,root,-)
%{_datadir}/geuzen-ux-panels/video
%{_datadir}/geuzen-ux-panels/panels/videos.panel
# >> files video
# << files video

%files photos
%defattr(-,root,root,-)
%{_datadir}/geuzen-ux-panels/photos
%{_datadir}/geuzen-ux-panels/panels/photos.panel
# >> files photos
# << files photos

%files music
%defattr(-,root,root,-)
%{_datadir}/geuzen-ux-panels/music
%{_datadir}/geuzen-ux-panels/panels/music.panel
# >> files music
# << files music

%files ifcfg
%defattr(-,root,root,-)
%{_datadir}/geuzen-ux-panels/ifcfg
%{_datadir}/geuzen-ux-panels/panels/ifcfg.panel
# >> files ifcfg
# << files ifcfg

%files mytablet
%defattr(-,root,root,-)
%{_datadir}/geuzen-ux-panels/mytablet
%{_datadir}/geuzen-ux-panels/panels/mytablet.panel
# >> files mytablet
# << files mytablet

%files meta-tablet
%defattr(-,root,root,-)
# >> files meta-tablet
# << files meta-tablet

