# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
%if X%{_vendor} == "Xmeego"
%define my_buildhost "meego"
%else
%define my_exec_dir "/usr/bin"
%if X%{_vendor} == "Xredhat"
%define qmake qmake-qt4 \
make
%else
%define qmake qmake \
make
%endif
%define qmake_install mkdir -p %{buildroot}%{my_exec_dir} && \
make INSTALL_ROOT=%{buildroot} install
%define my_buildhost non-meego-%{vendor}
%endif
# << macros

Name:       geuzen-qml-utils
Summary:    Geuzen QML Utilities
Version:    0.0.4
Release:    2
Group:      System/Libraries
License:    LGPL 2.1
URL:        http://moui.sourceforge.net
Source0:    %{name}-%{version}.tar.bz2
Source100:  geuzen-qml-utils.yaml
Requires:   /bin/sh
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(QtCore)
BuildRequires:  gcc-c++


%description
Common Geuzen QML components




%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/moui/geuzen/utils/libgeuzen-qml-utils.so
%{_libdir}/qt4/imports/moui/geuzen/utils/qmldir
# >> files
# << files


